apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: nginx # I put my created namespace name "nginx". You just find your namespace name and put it there. 
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /media/storage/kubernetes_temp # Add your own storage path. Remember this is not your local computer storage path. This is your worker node docker container storage path. You can easily view it go inside this to go docker worker node container. 
  
